; ============================================================
;  PlatformIO project configuration
;  ESP32 Power Monitor & Control
; ============================================================
[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

build_flags =
    -DCORE_DEBUG_LEVEL=0

lib_deps =
    ESP32Async/ESPAsyncWebServer @ ^3.7.6
    ESP32Async/AsyncTCP          @ ^3.3.6
    bblanchon/ArduinoJson        @ ^7.3.1
    Links2004/WebSockets         @ ^2.6.1
